### ISSUE TITLE
pip timeout issues

### ISSUE THREAD

**Issue by sparklyballs** [linuxserver/docker-baseimage-python27#4]
some users reporting non starting container , logs showing pip timeout issues.

look at possibly implementing some of the information here.

http://stackoverflow.com/questions/9847470/pip-search-django-produces-time-out-error

thanks @IronicBadger for the link.

**Comment by sparklyballs** [comment]
#5

**Comment by zaggash** [comment]
Maybe do not update the whole baseimage.
But on dedicated container, use requirement.txt and pip / pip-sync to update needed packages.

**Comment by sparklyballs** [comment]
@zaggash i see where you are coming from.
however the requirment for interacting with some of the external providers that our downstream containers use is no longer served by this update routine.
python dist-utils installed apps are no longer able to be updated via pip as of the latest pip version.

i'm of the opinion it serves no purpose anymore (the script) and at certain times it's actually detrimental as it stops the downstream container starting up.

**Comment by sparklyballs** [comment]
should state that the packages concerned are now compiled in the main dockerfile of the baseimage.
